Rational numbers module
mimuw-jnp2-rust/project-matrix-busters pull request #2
Opened 2022-11-14 13:31 UTC by tudny

Added rational numbers module
Added tests
Added LaTeX trait

2022-11-14 14:02 UTC, mgr0dzicki reviewed
Piękny kodzik

2022-11-14 14:02 UTC, mgr0dzicki commented on src/rationals.rs
> +/// The sign of the rational number is always stored in the numerator.
Probably it is also worth mentioning here that gcd(numerator, denominator)=1 (required by comparisons, right?)

2022-11-14 14:02 UTC, mgr0dzicki commented on src/rationals.rs
> +impl Eq for Rational {}
It's enough to use #[derive(Debug, Eq, PartialEq)]

2022-11-14 14:02 UTC, mgr0dzicki commented on src/rationals.rs
> +    fn mul(self, other: Self) -> Self {
I'd use checked_mul and return Option<Self> (and same for other ops). Overflows aren't even checked in release build, I think it'd better to somehow notify the user and stop the calculations.

2022-11-14 14:02 UTC, mgr0dzicki commented on src/rationals.rs
> +#[derive(Debug)]
What about Clone and Copy?

2022-11-15 19:06 UTC, mgr0dzicki requested changes

2022-11-15 19:06 UTC, mgr0dzicki commented on README.md
What about adding num in libraries?

2022-11-15 19:06 UTC, tudny commented on README.md
who asked

2022-11-15 19:08 UTC, mgr0dzicki commented on README.md
https://docs.rs/num/latest/num/

2022-11-15 19:12 UTC, merged