Matrix operations
mimuw-jnp2-rust/project-matrix-busters pull request #6
Opened 2022-11-21 16:07 UTC by tudny

2022-11-23 00:04 UTC, mgr0dzicki commented on src/matrices.rs
> +            return Err(anyhow::anyhow!("Matrices have different number of rows!"));
`return Err(anyhow::anyhow!(...));` $\equiv$ `anyhow::bail!(...)`

2022-11-28 14:04 UTC, tudny commented
This was the ugliest conflict I had to deal with

2022-11-29 09:14 UTC, tudny commented on src/matrices.rs
> +}
@mgr0dzicki check out those wild macros!

2022-12-01 21:23 UTC, mgr0dzicki requested changes

2022-12-01 21:23 UTC, mgr0dzicki commented on src/main.rs
> +extern crate core;
why

2022-12-01 21:24 UTC, tudny commented on src/main.rs
> +extern crate core;
how asked

2022-12-01 21:30 UTC, mgr0dzicki approved these changes

2022-12-01 21:32 UTC, mgr0dzicki approved these changes

2022-12-01 21:42 UTC, mgr0dzicki approved these changes
niech ci będzie

2022-12-01 21:42 UTC, merged